version: "3"

services:
  landscape_db:
    container_name: 'landscape_db'
    image: postgres:10
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=landscape
      - PGDATA=/pgdata
    volumes:
      - ./data/postgresql:/pgdata
      - ./data/pgdumps:/pgdumps

  landscape_redis:
    container_name: 'landscape_redis'
    image: redis:4-alpine
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/data
      - ./etc/redis.conf:/etc/redis.conf
    command: redis-server /etc/redis.conf

  landscape_search:
    container_name: 'landscape_search'
    image: elasticsearch:5-alpine
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx512m"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
      - '9300:9300'

  landscape_app:
    container_name: 'landscape_app'
    image: landscape/landscape
    env_file:
      - app.secret.env
      - app.local.env
    links:
      - landscape_search
      - landscape_db
      - landscape_redis
    logging:
      options:
        max-size: "1g"
        max-file: "10"
    environment:
      - DATABASE_NAME=landscape
      - DATABASE_HOST=landscape_db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    volumes:
      - ./data/uploads:/home/app/homeland/public/uploads
      - ./data/shared/cache/uploads-thumb:/home/app/cache/uploads-thumb
      - ./data/log:/home/app/homeland/log
      - ./data/tmp:/home/app/homeland/tmp
    command: /home/app/homeland/bin/docker-start
    ports:
      - "3000:3000"

  landscape_nginx:
    container_name: landscape_nginx
    restart: always
    image: landscape/landscape
    ports:
      - 8080:80
    links:
      - landscape_app
    command: nginx -c /etc/nginx/nginx.conf
    volumes:
      - ./data/uploads:/home/app/homeland/public/uploads
      - ./data/shared/cache/uploads-thumb:/home/app/cache/uploads-thumb
      - ./data/log:/home/app/log
      - ./data/tmp:/home/app/tmp
      - ./data/pids:/home/app/pids

